_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5  # Probabilité de flip horizontal
  - _target_: torchvision.transforms.RandomRotation
    degrees: 15  # Rotation aléatoire de +/- 15 degrés
  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.2  # Ajustement de la luminosité avec un facteur choisi aléatoirement entre [0.8, 1.2]
    contrast: 0.1  # Ajustement optionnel du contraste
    saturation: 0.1  # Ajustement optionnel de la saturation
  - _target_: torchvision.transforms.RandomAffine
    degrees: 0
    translate: [0.1, 0.1]  # Translation de 10% max dans chaque direction X et Y
    scale: [0.9, 1.1]  # Échelle de l'image entre 90% et 110%
    shear: 10  # Cisaillement de +/- 10 degrés
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]