defaults:
  - image_generator: finetune_sdxl
  - dataset_generator: base_pro

data_dir: ${root_dir}/dataset
root_dir:  ${hydra:runtime.cwd}
batch_size: 2
label: MORBIER



get_val:
  _target_: data.dataset_generators.get_val.Get_val
  real_images_val_path: ${data_dir}/val
  batch_size: 1
  num_workers: 6


labels_file: ${root_dir}/list_of_cheese.txt

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true