defaults:
  - train_transform: simple
  - test_transform: simple

name: clip_prompts
num_classes: 37
batch_size: 4
num_workers: 6
train_path: ${data_dir}/train/clip_prompts
real_images_val_path: ${data_dir}/val
test_path: ${data_dir}/test
